version: '3'

services:
  api:
    container_name: eif-api
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    volumes:
      - ./:/app/
    environment:
      - POSTGRES_DB=evening-is-food
      - POSTGRES_USER=eifroot
      - POSTGRES_PASSWORD=eifrootpwd
      - POSTGRES_HOST=eif-postgres
      - POSTGRES_PORT=5432
