version: '3'

services:
  postgres:
    container_name: eif-postgres
    image: postgres:14.2
    volumes:
      - ./docker/data/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=evening-is-food
      - POSTGRES_USER=eifroot
      - POSTGRES_PASSWORD=eifrootpwd
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"
