version: '3'

services:
  api:
    container_name: eif-api
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - "8686:9999"
    volumes:
      - ./:/app/
    environment:
      - POSTGRES_DB=eif
      - POSTGRES_USER=eifrootuser
      - POSTGRES_PASSWORD=eifpassword
      - POSTGRES_HOST=eif-postgres
      - POSTGRES_PORT=5432